# Generated by Django 4.2.27 on 2026-01-05 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('POTHOLE', 'Pothole'), ('ELECTRICITY', 'Electricity Failure'), ('WATER', 'Water Supply Issue'), ('GARBAGE', 'Garbage Collection'), ('STREETLIGHT', 'Street Light'), ('DRAINAGE', 'Drainage Problem'), ('ROAD', 'Road Damage'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=100)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='issue_images/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('ai_classification', models.CharField(blank=True, choices=[('POTHOLE', 'Pothole'), ('ELECTRICITY', 'Electricity Failure'), ('WATER', 'Water Supply Issue'), ('GARBAGE', 'Garbage Collection'), ('STREETLIGHT', 'Street Light'), ('DRAINAGE', 'Drainage Problem'), ('ROAD', 'Road Damage'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('ai_priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20, null=True)),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_phone', models.CharField(max_length=15)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('authority_notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='user_civici_status_b82f95_idx'), models.Index(fields=['issue_type', 'area'], name='user_civici_issue_t_9f1dff_idx'), models.Index(fields=['latitude', 'longitude'], name='user_civici_latitud_7026a0_idx')],
            },
        ),
    ]
