# Generated by Django 5.2.3 on 2026-01-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civicissue',
            name='ai_classification',
            field=models.CharField(blank=True, choices=[('POTHOLE', 'Potholes'), ('GARBAGE', 'Garbage overflow'), ('WATER', 'Water leakage'), ('STREETLIGHT', 'Broken streetlights'), ('ROAD_OBSTRUCTION', 'Road obstruction')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='civicissue',
            name='issue_type',
            field=models.CharField(choices=[('POTHOLE', 'Potholes'), ('GARBAGE', 'Garbage overflow'), ('WATER', 'Water leakage'), ('STREETLIGHT', 'Broken streetlights'), ('ROAD_OBSTRUCTION', 'Road obstruction')], default='OTHER', max_length=20),
        ),
    ]
