# Generated by Django 5.2.3 on 2026-01-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_civicissue_ai_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civicissue',
            name='image_labels',
            field=models.TextField(blank=True, help_text='AI-detected labels for the uploaded image', null=True),
        ),
        migrations.AlterField(
            model_name='civicissue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issues/'),
        ),
    ]
